### ISSUE TITLE
Can this be made compatible with node 16.15.1 which is LTS?

### ISSUE THREAD

**Issue by tim-kos** [cpietsch/sharpsheet#6]
The module is node >= 17, but 17 isn't LTS yet. What would be required to make it work with node 16.15.1? Also happy to fork and submit a PR if you have a pointer.

**Comment by cpietsch** [comment]
That is a good question. Actually everything works with the latest LTS.
Made a commit and also updated the dependencies: https://github.com/cpietsch/sharpsheet/commit/47a1fc54141d00400ef25ae9b94383667a960f91
Version 0.0.8

**Comment by tim-kos** [comment]
Much love for the quick turnaround on this one.
